name: Auto Release

on:
  push:
    branches:
      - main          # or your default branch
  workflow_dispatch:  # manual trigger

jobs:
  build-and-release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository (w/ submodules)
        uses: actions/checkout@v3
        with:
          fetch-depth: 0           # fetch all history
          submodules: recursive    # pull in all submodules
      
      - name: Create tar.gz archive
        run: |
          REVISION=${GITHUB_SHA::7}
          ARCHIVE_NAME=c-libp2p-${GITHUB_REF_NAME}-${REVISION}.tar.gz
          tar --warning=no-file-changed czf $ARCHIVE_NAME --exclude='.git' .
          echo "ARCHIVE_NAME=$ARCHIVE_NAME" >> $GITHUB_OUTPUT

      - name: create tar.gz archive
        id: tar_step
        run: |
          REVISION=${GITHUB_SHA::7}
          ARCHIVE_NAME=c-libp2p-${GITHUB_REF_NAME}-${REVISION}.tar.gz
          tar -czf $ARCHIVE_NAME --exclude='.git' .
          echo "ARCHIVE_NAME=$ARCHIVE_NAME" >> $GITHUB_OUTPUT
      
      - name: upload tar.gz to release
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ${{ steps.tar_step.outputs.ARCHIVE_NAME }}
          asset_name: ${{ steps.tar_step.outputs.ARCHIVE_NAME }}
          asset_content_type: application/gzip
