name: create release tarball

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build_and_release:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repository with submodules
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: get short commit sha
        id: get_sha
        run: echo "sha=$(git rev-parse --short HEAD)" >> "$GITHUB_OUTPUT"

      - name: create tar.gz archive
        run: |
          project_name=$(basename "$GITHUB_REPOSITORY")
          tar_name="${project_name}-${{ steps.get_sha.outputs.sha }}.tar.gz"
          tar --exclude="./.git" --exclude="./.github" --exclude="$tar_name" -czf "$tar_name" .
          echo "tar_name=$tar_name" >> "$GITHUB_ENV" # this is kinda hacky lol

      - name: create release
        uses: softprops/action-gh-release@v1
        with:
          files: ${{ env.tar_name }}
          tag_name: ${{ github.ref_name }}-${{ steps.get_sha.outputs.sha }}
          name: release ${{ github.ref_name }} (${{ steps.get_sha.outputs.sha }})
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
